@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NDkzNDI3NSwiZXhwIjoxNjg0OTM1MTc1fQ.n9PlfjLobV3vwMkPvEiMGMbig7PLFj6NA-BQbH2Gw6w
@url=http://localhost:3000
###
### Create Order
###

POST {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1
}


###
### Update Order Status
###

PUT {{url}}/orders/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "complete"
}


###
### Get Active Order
###

GET {{url}}/orders/1/active
Authorization: Bearer {{token}}


###
### Get Completed Orders
###

GET {{url}}/orders/1/completed
Authorization: Bearer {{token}}


###
### Add Product to Order
###

POST {{url}}/orders/2/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "product_id": 2,
  "quantity": 1
}


###
### Remove Product from Order
###

DELETE {{url}}/orders/1/products/1
Authorization: Bearer {{token}}


###
### Get Ordered Products
###

GET {{url}}/orders/1/orderedProducts
Authorization: Bearer {{token}}


###
### Get Total Amount for All Orders
###

GET {{url}}/orders/1/totalAmountForAllOrders
Authorization: Bearer {{token}}