@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NTI2OTU3NCwiZXhwIjoxNjg1MjcwNDc0fQ.HDe46QnoithA8hEcrwsHZZ48aCIqUj9DAOUc01_upsY
@url=http://localhost:3000
###
### Create Order
###

POST {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1
}


###
### Update Order Status
###

PUT {{url}}/orders/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "complete"
}


###
### Get Active Order
###

GET {{url}}/orders/users/1/active
Authorization: Bearer {{token}}


###
### Get Completed Orders
###

GET {{url}}/orders/users/1/completed
Authorization: Bearer {{token}}


###
### Add Product to Order
###

POST {{url}}/orders/users/1/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "product_id": 1,
  "quantity": 1
}


###
### Remove Product from Order
###

DELETE {{url}}/orders/users/1/products/1
Authorization: Bearer {{token}}

