@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY4NDY3ODA5NCwiZXhwIjoxNjg0Njc4OTk0fQ.gZTfgCDHMEFyGtvk3bAQpEY1uAYk8Cp84maKsqlHn4U
@url=http://localhost:3000
###
### Create Order
###

POST {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1
}


###
### Update Order Status
###

PUT {{url}}/orders/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "complete"
}


###
### Get Active Order
###

GET {{url}}/orders/1/active
Authorization: Bearer {{token}}


###
### Get Completed Orders
###

GET {{url}}/orders/1/completed
Authorization: Bearer {{token}}


###
### Add Product to Order
###

POST {{url}}/orders/1/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "product_id": 1,
  "quantity": 2
}


###
### Remove Product from Order
###

DELETE {{url}}/orders/1/products/1
Authorization: Bearer {{token}}


###
### Get Ordered Products
###

GET {{url}}/orders/1/orderedProducts
Authorization: Bearer {{token}}


###
### Get Total Amount for All Orders
###

GET {{url}}/orders/1/totalAmountForAllOrders
Authorization: Bearer {{token}}