@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NTI2OTU3NCwiZXhwIjoxNjg1MjcwNDc0fQ.HDe46QnoithA8hEcrwsHZZ48aCIqUj9DAOUc01_upsY
@url=http://localhost:3000
###
### Get All Products
###

GET {{url}}/products
Authorization: Bearer {{token}}


###
### Get Product by ID
###

GET {{url}}/products/1
Authorization: Bearer {{token}}


###
### Create Product
###

POST {{url}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Product 2",
  "description": "cái gì gì đây 1",
  "price": 1099
}


###
### Update Product
###

PUT {{url}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Product 1",
  "description": "Updated cái gì gì đây",
  "price": 19.99
}


###
### Delete Product
###

DELETE {{url}}/products/1
Authorization: Bearer {{token}}

###
### Get Ordered Products
###

GET {{url}}/orders/1/orderedProducts
Authorization: Bearer {{token}}


###
### Get Total Amount for All Orders
###

GET {{url}}/orders/1/totalAmountForAllOrders
Authorization: Bearer {{token}}