@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY4NDY3ODA5NCwiZXhwIjoxNjg0Njc4OTk0fQ.gZTfgCDHMEFyGtvk3bAQpEY1uAYk8Cp84maKsqlHn4U
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY4NDY3ODA5NCwiZXhwIjoxNjg1MjgyODk0fQ.MKw2djexc59es9YLNtgKxjbLXxMIoJg0p6rpLT0Tz1c
@url=http://localhost:3000
###
### Get All Users
###

GET {{url}}/users
Authorization: Bearer {{token}}


###
### Get User by ID
###

GET {{url}}/users/1
Authorization: Bearer {{token}}


###
### Create User
###

POST {{url}}/users
Content-Type: application/json

{
  "username": "user1",
  "email": "abc@gmail.com",
  "password": "123",
  "first_name": "Tinh",
  "last_name": "Le"
}


###
### Update User
###

PUT {{url}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "user1update",
  "email": "abc1@gmail.com",
  "password": "1234",
  "first_name": "Tinh",
  "last_name": "Le"
}


###
### Delete User
###

DELETE {{url}}/users/1
Authorization: Bearer {{token}}


###
### Authenticate
###

POST {{url}}/authenticate
Content-Type: application/json

{
  "username": "user1",
  "password": "123"
}


###
### Login
###

POST {{url}}/login
Content-Type: application/json

{
  "username": "user1",
  "password": "123"
}


###
### Refresh Token
###

POST {{url}}/refreshtoken
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}