@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NTI2OTU3NCwiZXhwIjoxNjg1MjcwNDc0fQ.HDe46QnoithA8hEcrwsHZZ48aCIqUj9DAOUc01_upsY

@url=http://localhost:3000
###
### Get All Users
###

GET {{url}}/users
Authorization: Bearer {{token}}


###
### Get User by ID
###

GET {{url}}/users/1
Authorization: Bearer {{token}}


###
### Create User
###

POST {{url}}/users
Content-Type: application/json

{
  "username": "user1",
  "email": "abc@gmail.com",
  "password": "123",
  "first_name": "Tinh",
  "last_name": "Le"
}


###
### Update User
###

PUT {{url}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "user1",
  "email": "abc1@gmail.com",
  "password": "1234",
  "first_name": "Tinh",
  "last_name": "Le"
}


###
### Delete User
###

DELETE {{url}}/users/1
Authorization: Bearer {{token}}


###
### Authenticate
###

POST {{url}}/authenticate
Content-Type: application/json

{
  "username": "user1",
  "password": "123"
}


###
### Login
###

POST {{url}}/login
Content-Type: application/json

{
  "username": "user1",
  "password": "123"
}


###
### Refresh Token
###
